start: 
	gcc  date.c -o date_
	gcc  ls.c -o ls_
	gcc  mkdir.c -o mkdir_
	gcc  rm.c -o rm_
	gcc  cat.c -o cat_
	gcc shell.c -o thread -lpthread
	./thread

clear: 
	rm rm_
	rm cat_
	rm mkdir_
	rm date_
	rm ls_
	rm thread